### ISSUE TITLE
Short captions possible via lua filter

### ISSUE THREAD

**Issue by joelostblom** [tompollard/phd_thesis_markdown#91]
@tompollard I saw that you are looking for a way to add short captions, so I wanted to bring your attention to this [lua-filter](https://github.com/pandoc/lua-filters/tree/master/short-captions), which I am currently using for my thesis and that is working really well so far. The syntax is as follows.

```markdown
![The long caption](foo.png){short-caption="a short caption"} 
```

It is compatible with other pandoc extensions such as pandoc-crossref mentioned in #68.

**Comment by tompollard** [comment]
good to know, thanks @joelostblom! it's been a while since i looked at this repo. would be good to incorporate this suggestion, as well as https://github.com/tompollard/phd_thesis_markdown/issues/92

**Comment by maawoo** [comment]
I second this approach of using the short-caption lua filter. 
I'm using the pandoc-fignos and -tablenos [tag feature](https://github.com/tomduck/pandoc-fignos#tagged-figures) so that figures and tables in my appendix appear as "A-1",  "A-2" , "B-1" and so on for each appendix. For some reason this doesn't work when I'm using the default  `--filter=pandoc-shortcaption`. The short-caption lua filter works, however 👍🏻
